name: Run Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - tests/test_login.py
          - tests/test_edit_info.py

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r POM_OrangeHRM/requirements.txt

      - name: Run tests with pytest
        run: |
          pytest -v ${{ matrix.suite }} --maxfail=1 --disable-warnings -q